"""create request history table

Revision ID: e1f191f21746
Revises: 
Create Date: 2026-07-28 16:14:15.624496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1f191f21746'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cadastral_number', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('result', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_history_cadastral_number'), 'request_history', ['cadastral_number'], unique=False)
    op.create_index(op.f('ix_request_history_id'), 'request_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_history_id'), table_name='request_history')
    op.drop_index(op.f('ix_request_history_cadastral_number'), table_name='request_history')
    op.drop_table('request_history')
    # ### end Alembic commands ###
